function createfigure_convergence(X1, Y1, X2, Y2)
%CREATEFIGURE1(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 16-Feb-2019 17:26:24

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','ADP1');

% Create plot
plot(X2,Y2,'DisplayName','ADP');

% Create xlabel
xlabel('iteration');

% Create title
title('COIL20');

% Create ylabel
ylabel('||F^{(t+1)} -  F^{(t)}||_F');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 0.5]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'YTick',[0 0.1 0.2 0.3 0.4 0.5]);
% Create legend
legend(axes1,'show');

